### ISSUE TITLE
[bug] Cannot operate SQLite3 in multi-thread case

### ISSUE THREAD

**Issue by BernieHuang2008** [BernieHuang2008/MercurySQL#18]
**Describe the bug**
when using it with flask, sqlite3 not supported to create a new cursor.

**How To Reproduce?**

**Expected behavior**

**Additional context**

```python
Traceback (most recent call last):
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
  File "g:\git\BernieHuang2008\MercurySQL\__local\test\bug1\user.py", line 36, in reg
    if (table_users["username"] == username).query():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\MercurySQL\core.py", line 933, in query
    res = self.table.db.do(cmd, paras=[paras])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\git\BernieHuang2008\MercurySQL\.venv\Lib\site-packages\MercurySQL\core.py", line 179, in do
    c = self.conn.cursor()
        ^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8632 and this is thread id 8936.
```

**Comment by BernieHuang2008** [comment]
In this case i decided to use a connection pool.

Here are some answers provided by guitar copilot in this issue.

---

In general, Python SQL ORMs such as SQLAlchemy, Django ORM, or Peewee handle thread safety for you. They use connection pooling and maintain thread-local connections to ensure that each thread has its own exclusive connection to the database.

- **Connection Pooling**: Most ORMs use connection pooling under the hood. A connection pool is a cache of database connections that can be reused, which reduces the overhead of establishing a new connection for each query.

- **Thread-Local Connections**: ORMs usually maintain thread-local connections. This means that each thread gets its own unique connection that it doesn't share with any other thread. This approach avoids the issue of sharing SQLite objects between threads.

For single-threaded applications, these ORMs will just use the single connection provided by the pool. There's no need to open multiple connections or threads in this case. The ORM can't detect whether your program is single-threaded or multi-threaded, but it doesn't need to. It simply provides a connection for each thread that asks for one.

**Comment by BernieHuang2008** [comment]
There may be a solution: we can use `queue.Queue` to communicate across threads
